### ISSUE TITLE
Remove duplicate images

### ISSUE THREAD

**Issue by engnadeau** [Nadeau-Innovations/site#157]
- Found duplicates: https://docs.google.com/spreadsheets/d/16ZSR35hCNXqdB3-Q4DGOTXJXMSNfTsSn4zkFyOBCdPo/edit?usp=sharing
- Use `filename` to get images from `assets/media`, e.g.,:

```yaml
# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  filename: "3dp-lab.jpg"
  caption: ""
  focal_point: ""
  preview_only: false
```

- See https://github.com/wowchemy/wowchemy-hugo-themes/pull/2799/files for details
